apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/robertoporfiroIEU/intro-argo-cd-tutorial'
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
